# Generated by Django 6.0.7 on 2026-07-17 12:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Номер телефона должен содержать 9-15 цифр', regex='^\\+?1?\\d{9,15}$')])),
                ('comment', models.TextField()),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Положительный'), ('neutral', 'Нейтральный'), ('negative', 'Отрицательный')], max_length=10, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(blank=True, choices=[('inquiry', 'Запрос'), ('feedback', 'Отзыв'), ('collaboration', 'Сотрудничество'), ('support', 'Поддержка'), ('other', 'Другое')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Отправка контактных данных',
                'verbose_name_plural': 'Отправки контактных данных',
                'ordering': ['-created_at'],
            },
        ),
    ]
